Team4_FinalProject/Team4_FinalProject/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Team4_FinalProject.Models
{
    public class Ticket
    {
        [Key]
        public int TicketId { get; set; }

        [Required(ErrorMessage ="Must specify an issue")]
        [StringLength(100, ErrorMessage = "Issue must be less than 100 characters")]
        public string Issue { get; set; }

        public DateTime DateOpened { get; set; }

        public string Status { get; set; }

        public List<Note> Notes { get; set; }

        //Establishing Many to One with user
        public int UserId { get; set; }
        public User  User { get; set; }


    }
}

Team4_FinalProject/Team4_FinalProject/Controllers/NoteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Team4_FinalProject.Models;

namespace Team4_FinalProject.Controllers
{
    public class NoteController : Controller
    {
        private TicketManagerDbContext context { get; set; }
        public NoteController(TicketManagerDbContext ctx) => context = ctx;

        [HttpGet]
        public ViewResult Add(int id)
        {
            Note n = new();
            n.TicketId = id;
            return View(n);
        }

        [HttpPost]
        public IActionResult Add(Note n)
        {
            if (ModelState.IsValid)
            {
                //n.TicketId = ticketId;
                //ViewBag.TicketId = ticketId;
                if (n.NoteId == 0)
                {
                    context.Notes.Add(n);
                    context.SaveChanges();
                }
                var routeId = new RouteValueDictionary
                {
                    {"id", n.TicketId}
                };
                return RedirectToAction("Details", "Ticket", routeId);
            }
            else
            {
                ModelState.AddModelError("", "Something is wrong with the input! Try again.");
                return View(n);
            }
        }
        //[HttpGet]
        //public IActionResult Add()
        //{
        //    Note n = new Note();
        //    return View(n);
        //}

        //    [HttpPost]
        //public IActionResult Add(int id)
        //{

        //    n.DateCreated = DateTime.Now;
        //    n.TicketId = id;
        //    if (ModelState.IsValid)
        //    {
        //        if (n.NoteId == 0)
        //            context.Notes.Add(n);
        //        context.SaveChanges();
        //        return RedirectToAction("Detail", "Ticket");
        //    }
        //    else
        //    {
        //        //return RedirectToAction("Detail", "Ticket");
        //        return View(n);
        //    }
    }
}

Team4_FinalProject/Team4_FinalProject/Controllers/TicketController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Team4_FinalProject.Models;

namespace Team4_FinalProject.Controllers
{
    public class TicketController : Controller
    {
        private TicketManagerDbContext context;

        public TicketController(TicketManagerDbContext ctx)
        {
            context = ctx;
        }
        public IActionResult Index()
        {
            return View("List");
        }

        [HttpGet]
        public IActionResult Add(int id)
        {
            //To display user name
            var user = context.Users.Find(id);
            ViewBag.User = user;
            Ticket model = new();
            model.UserId = id;
            return View(model);
        }

        [HttpPost]
        public IActionResult Add(Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                context.Tickets.Add(ticket);
                context.SaveChanges();
                return RedirectToAction("Index", "Home");
                
            }
            else
            {
                ViewBag.User = context.Users.Find(ticket.UserId);
                ModelState.AddModelError("Invalid", "Model State was invalid what did you do?");
                return View(ticket);
            }
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            Ticket ticket = context.Tickets.Find(id);
            ViewBag.Ticket = ticket;
            ViewBag.TicketId = id;
            //Also grabbing tickets like I showed in others I don't know how to load related
            //Entities whilst grabbing only one entity 
            List<Note> notes = context.Notes.Where(c => c.TicketId == id).ToList();
            ViewBag.Notes = notes;
            return View(ticket);
        }
    }
}

Team4_FinalProject/Team4_FinalProject/Views/Ticket/Add.cshtml
@model Ticket

@{
    ViewData["Title"] = "Add Ticket";
}
<style>
    #name{
        display: inline-block;
        animation:fadingin 2s;
    }
</style>
<h2 class="display-4">Add Ticket For <span id="name" class="text-primary">@ViewBag.User.FirstName @ViewBag.User.LastName</span></h2>

<form asp-action="Add" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Issue">Issue Description</label>
        <textarea rows="8" asp-for="Issue" class="form-control"></textarea>
    </div>
    @if (ViewBag.User.IsTechnician == true)
    {
        <div class="form-group">
            <label asp-for="Status">Status</label>
            <select asp-for="Status" class="form-control">
                <option value="In Progress">In Progress</option>
                <option value="Completed">Completed</option>
            </select>
        </div>
    }
    <input type="hidden" asp-for="TicketId" />
    <input type="hidden" asp-for="UserId" />

    <button class="btn btn-primary" type="submit">Add</button>
    <button class="btn btn-primary" type="submit" asp-area="" asp-controller="Home" asp-action="Index">Cancel</button>
</form>

Team4_FinalProject/Team4_FinalProject/Views/Ticket/Details.cshtml
@model Ticket

@{
    ViewData["Title"] = " | Ticket Details";
   
}

<h1 style="margin-bottom: 1em;">Ticket Details</h1>

<h3 class="m-2"><span class="text-primary">Date Created:</span> @ViewBag.Ticket.DateOpened</h3>

<h3 class="m-2"><span class="text-primary">Status:</span> @ViewBag.Ticket.Status</h3>

<h3 class="m-2"><span class="text-primary">Issue:</span> </h3>

<p class="p-2 border" style="font-size: 1.4em; min-height: 10em;">@ViewBag.Ticket.Issue</p>

<a asp-controller="Note" asp-action="Add" class="btn btn-primary" asp-route-id="@ViewBag.Ticket.TicketId">Add Note</a>
<a asp-controller="Home" asp-action="Index" class="btn btn-primary" asp-route-id="@ViewBag.User">Return to Ticket List</a>

<h3 class="m-2 text-primary">Notes: </h3>
@*<a class="btn btn-primary mb-2" asp-controller="Note" asp-action="Add" asp-route-id="@ViewBag.Ticket.TicketId">Add Note</a>*@
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Note Id</th>
            <th>Content</th>
            <th>Date Opened</th>
            @*<th></th>*@
        </tr>
    </thead>
    <tbody>
        @foreach (Note note in ViewBag.Notes)
        {
            <tr>
                <td>@note.NoteId</td>
                <td>
                    <div style="word-wrap: break-word">@note.Content</div>
                </td>
                <td>@note.DateCreated</td>
                @*<td>
                        <a asp-controller="Note" asp-route-id="@note.NoteId" asp-action="Details">View Details</a>
                    </td>*@
            </tr>
        }
    </tbody>
</table>

Team4_FinalProject/Team4_FinalProject/Views/Ticket/Index.cshtml
@model IEnumerable<Ticket>
@{ 
    ViewBag.Title = "Ticket List";
}

<h2 class="display-4">Ticket List</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Ticket ID</th>
            <th>Opened By</th>
            <th>Issue Description</th>
            <th>Ticket Status</th>
            <th>Date Opened</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(Ticket ticket in Model)
            {
                <tr>
                    <td>@ticket.TicketId</td>
                    <td>@ticket.UserId</td>
                    <td>@ticket.Category</td>
                    <td>@ticket.Status</td>
                    <td>@ticket.DateOpened</td>
                    <td>
                        <a asp-controller="Ticket" asp-action="Detail" asp-route-id="@ticket.TicketId">View Details</a>
                    </td>
                </tr>
            }      
    </tbody>
</table>

Team4_FinalProject/Team4_FinalProject/Views/Ticket/List.cshtml
@*@model TicketListViewModel
@{ 
    ViewBag.Title = "Ticket List";
}

<h2 class="display-4">Ticket List</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Ticket ID</th>
            <th>Issue Description</th>
            <th>Ticket Status</th>
            <th>Date Opened</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(Ticket ticket in Model.Tickets)
            {
                <tr>
                    <td>@ticket.TicketId</td>
                    <td>@ticket.Issue</td>
                    <td>@ticket.Status</td>
                    <td>@ticket.DateOpened</td>
                    <td>
                        <a asp-controller="Ticket" asp-action="Details" asp-route-id="@ticket.TicketId">View Details</a>
                    </td>
                </tr>
            }      
    </tbody>
</table>*@