Team4_FinalProject/Team4_FinalProject/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Team4_FinalProject.Models;
using Team4_FinalProject.ViewModels;
using Microsoft.AspNetCore.Http;

namespace Team4_FinalProject.Controllers
{
    public class LoginController : Controller
    {
        private TicketManagerDbContext context;

        public LoginController(TicketManagerDbContext ctx)
        {
            context = ctx;
        }
        
        public IActionResult Index()
        {
            var model = new LoginViewModel();
            
            return View(model);
        }

        [HttpPost]
        public IActionResult Index(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var user = context.Users.Single(u => u.Username == model.Username);
                    if (user.Password == model.Password)
                    {
                        HttpContext.Session.SetInt32("user_id", user.UserId);
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Passwords Do Not Match");
                        return View(model);
                    }
                }
                catch {
                    ModelState.AddModelError("", "Username is not valid");
                    return View(model);
                };

            }
            else
            {
                return View(model);
            }
           
        }

        public IActionResult Logout(LoginViewModel model)
        {
                HttpContext.Session.Clear();
                return RedirectToAction("Index", "Home");
        }
    }
}

Team4_FinalProject/Team4_FinalProject/Controllers/TicketController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Team4_FinalProject.Models;

namespace Team4_FinalProject.Controllers
{
    public class TicketController : Controller
    {
        private TicketManagerDbContext context;

        public TicketController(TicketManagerDbContext ctx)
        {
            context = ctx;
        }
        public IActionResult Index()
        {
            return View("List");
        }

        [HttpGet]
        public IActionResult Add(int id)
        {
            //To display user name
            var user = context.Users.Find(id);
            ViewBag.User = user;
            Ticket model = new();
            model.UserId = id;
            return View(model);
        }

        [HttpPost]
        public IActionResult Add(Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                context.Tickets.Add(ticket);
                context.SaveChanges();
                return RedirectToAction("Index", "Home");
                
            }
            else
            {
                ViewBag.User = context.Users.Find(ticket.UserId);
                ModelState.AddModelError("Invalid", "Model State was invalid what did you do?");
                return View(ticket);
            }
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            Ticket ticket = context.Tickets.Find(id);
            ViewBag.Ticket = ticket;
            ViewBag.TicketId = id;
            //Also grabbing tickets like I showed in others I don't know how to load related
            //Entities whilst grabbing only one entity 
            List<Note> notes = context.Notes.Where(c => c.TicketId == id).ToList();
            ViewBag.Notes = notes;
            return View(ticket);
        }
    }
}

Team4_FinalProject/Team4_FinalProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IT Help Desk</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IT Help Desk</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (ViewData["User"] != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Ticket" asp-action="Add" asp-route-id="@TempData["userId"]">Add Ticket</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Login" asp-action="Logout">Log Out</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Login" asp-action="Index">Log In</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container text-light">
            &copy; 2021 - Team4_FinalProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>